[package]
rust-version.workspace = true
name = "sdkwork-routes-assets-app-api"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_routes_assets_app_api"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
chrono = "0.4"
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
sdkwork-drive-contract.workspace = true
sdkwork-drive-http.workspace = true
sdkwork-drive-workspace-service.workspace = true
sdkwork-routes-drive-app-api.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-web-core.workspace = true
tower.workspace = true
